[package]
name = "axum"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resolver_api = { path = "../.." }
resolver_api_derive = { path = "../../derive" }
tokio = { version = "1.32", features = ["full"] }
axum = { version = "0.6", features = ["json", "headers"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
async-trait = "0.1"
